{
    "swagger": 2.0,
    "info": {
        "version": "2.1",
        "description": "Under construction",
        "title": "Stores API"
    },
    "host": "api.bigcommerce.com",
    "basePath": "/stores/cl1xfm/v2",
    "schemes": [
        "https"
    ],
    "paths": {
        "/blog/posts": {
            "get": {
                "tags": [
                    "blog"
                ],
                "summary": "List blog posts associated with the store",
                "description": "Returns an array containing either all of the blog post objects associated with the store (up to 250) or just those blog post objects matching your query parameters.",
                "operationId": "getPosts",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_content",
                            "read:store_v2_content_read_only"
                        ]
                    }
                }
            },
            "post": {
                "tags": [
                    "blog"
                ],
                "summary": "Create a blog post",
                "description": "Allows you to create a new blog post.",
                "operationId": "createBlogPost",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_content",
                            "read:store_v2_content_read_only"
                        ]
                    }
                }
            },
            "delete": {
                "tags": [
                    "blog"
                ],
                "summary": "Delete all blog posts associated with the store",
                "description": "This operation deletes all of the blog posts in the store. Use with caution.",
                "operationId": "deleteBlogPosts",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_content",
                            "read:store_v2_content_read_only"
                        ]
                    }
                }
            }
        },
        "/blog/posts/{id}": {
            "get": {
                "tags": [
                    "blog"
                ],
                "summary": "Retrieve a single blog post",
                "description": "Returns the blog post that matches the <b>id</b> value provided in the path.",
                "operationId": "getPost",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_content",
                            "read:store_v2_content_read_only"
                        ]
                    }
                }
            },
            "put": {
                "tags": [
                    "blog"
                ],
                "summary": "Modify writeable values in existing blog post",
                "description": "Allows you to modify any or all of the writeable values in an existing blog post.",
                "operationId": "modifyPost",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_content",
                            "read:store_v2_content_read_only"
                        ]
                    }
                }
            },
            "delete": {
                "tags": [
                    "blog"
                ],
                "summary": "Delete a single blog post",
                "description": "Deletes the blog post that matches the <b>id</b> value sent in the path.",
                "operationId": "deletePost",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_content",
                            "read:store_v2_content_read_only"
                        ]
                    }
                }
            }            
        },
        "/blog/tags": {
            "get": {
                "tags": [
                    "blog"
                ],
                "summary": "List all blog tags associated with the store",
                "description": "Retrieves an array of all of the blog tags associated with the store, along with the id(s) of the blog posts that contain the tag.",
                "operationId": "getTags",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_content",
                            "read:store_v2_content_read_only"
                        ]
                    }
                }
            }
        },
        "/customer_groups": {
            "get": {
                "tags": [
                    "customers"
                ],        
                "summary": "Retrieve all or some customer groups",
                "description": "Allows you to retrieve all customer groups or to retrieve a single customer group by <b>name</b> value or <b>is_default</b> value.",
                "operationId": "getCustomerGroups",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            },
            "post": {
                "tags": [
                    "customers"
                ],        
                "summary": "Create a customer group",
                "description": "",
                "operationId": "createCustomerGroup",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            },
            "delete": {
                "tags": [
                    "customers"
                ],        
                "summary": "Delete one or more customer groups",
                "description": "",
                "operationId": "deleteCustomerGroups",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            }            
        },
        "/customer_groups/{id}": {
            "get": {
                "tags": [
                    "customers"
                ],        
                "summary": "Retrieve a single customer group",
                "description": "Returns the customer group object that has the same <b>id</b> value provided in the path.",
                "operationId": "getCustomerGroup",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            },
            "put": {
                "tags": [
                    "customers"
                ],
                "summary": "Modify writeable values in a customer group",
                "description": "Allows you to modify any or all of the writeable values in a customer group object.",
                "operationId": "modifyCustomerGroup",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            },
            "delete": {
                "tags": [
                    "customers"
                ],
                "summary": "Delete a single customer group",
                "description": "Deletes the customer group object that matches the <b>id</b> value sent in the path.",
                "operationId": "deleteCustomerGroup",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            }             
        },
        "/customers": {
            "get": {
                "tags": [
                    "customers"
                ],
                "summary": "List store customers",
                "description": "Returns an array containing either all of the store's customer objects (up to 250) or the customer objects matching your query parameter(s).",
                "operationId": "getCustomers",
                "security": {
                    "api_key": {},
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            },
            "post": {
                "tags": [
                    "customers"
                ],
                "summary": "Create a customer",
                "description": "Allows you to create a new customer object.",
                "operationId": "createCustomer",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            },  
            "delete": {
                "tags": [
                    "customers"
                ],
                "summary": "Delete one or more store customers",
                "description": "Use this method to delete all customers in the store or the customer(s) that match your query parameters.",
                "operationId": "deleteCustomers",
                "security": {
                    "api_key": {},
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            }            
        },
        "/customers/{id}": {
            "get": {
                "tags": [
                    "customers"
                ],        
                "summary": "Retrieve a single customer",
                "description": "Returns the customer object that has the same <b>id</b> value provided in the path.",
                "operationId": "getCustomer",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            },
            "put": {
                "tags": [
                    "customers"
                ],
                "summary": "Modify writeable values in a customer",
                "description": "Allows you to modify any or all of the writeable values in a customer object.",
                "operationId": "modifyCustomer",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            },
            "delete": {
                "tags": [
                    "customers"
                ],
                "summary": "Delete a single customer",
                "description": "Deletes the customer object that matches the <b>id</b> value sent in the path.",
                "operationId": "deleteCustomer",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            }
        },
        "/customers/{id}/addresses": {
            "get": {
                "tags": [
                    "customers"
                ],        
                "summary": "Retrieve all of the addresses associated with a customer",
                "description": "Returns an array containing all of addresses associated with a specific customer object. Include the <b>id</b> value of the customer object in the path.",
                "operationId": "getCustomerAddresses",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            },
        
            "post": {
                "tags": [
                    "customers"
                ],        
                "summary": "Create a customer address",
                "description": "Create a customer address object and optionally link it to an associated customer object by including the <b>id</b> of the customer object.",
                "operationId": "createCustomerAddress",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            },
            "delete": {
                "tags": [
                    "customers"
                ],
                "summary": "Delete all of the addresses associated with a customer",
                "description": "Deletes all of customer addresses associated with the customer. Include the <b>id</b> value of the customer object in the path.",
                "operationId": "deleteCustomerAddresses",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            }        
        },

        "/customers/{id}/addresses/{id}": {
            "get": {
                "tags": [
                    "customers"
                ],        
                "summary": "Retrieve a single customer address",
                "description": "Include the <b>id</b> value of the customer object in the part of the path before <b>addresses</b>. Include the <b>id</b> value of the customer address object in the part of the path after <b>addresses</b>.",
                "operationId": "getCustomerAddress",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            },
            "put": {
                "tags": [
                    "customers"
                ],        
                "summary": "Modify writeable values in a customer address",
                "description": "Allows you to modify any or all of the writeable values in an existing customer address. Include the <b>id</b> value of the customer object in the part of the path before <b>addresses</b>. Include the <b>id</b> value of the customer address object in the part of the path after <b>addresses</b>.",
                "operationId": "modifyCustomerAddress",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            },
            "delete": {
                "tags": [
                    "customers"
                ],
                "summary": "Delete one customer address",
                "description": "Include the <b>id</b> value of the customer object in the part of the path before <b>addresses</b>. Include the <b>id</b> value of the customer address object in the part of the path after <b>addresses</b>.",
                "operationId": "deleteCustomerAddress",
                "security": {
                    "stores_auth": {
                        "scopes": [
                            "write:store_v2_customers",
                            "read:store_v2_customers_read_only"
                        ]
                    }
                }
            }        
        }
    },

    "securityDefinition": {
        "api_key": {
            "type": "oauth2",
            "flow": "application"
        },
        "stores_auth": {
            "type": "oauth2",
            "scopes": [
                {
                    "name": "read:store_v2",
                    "description": "read your pets"
                }
            ]
        }
    }
}